appname: "PowerdnsTango"

layout: "main"

session: Storable
session_dir: /tmp/pdns_tango
session_expires: 3600

charset: "UTF-8"
template: "template_toolkit"
serializer: "JSON"

engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
  FlashMessage:
    token_name: flash
    session_hash_key: _flash
  Email:
    from: 'noreply@averna.id.au'
    subject: 'Powerdns Tango'
    driver: smtp
    host: localhost
  Database:
    driver: 'mysql'
    database: 'pdns_tango'
    host: 'localhost'
    port: 3306
    username: 'tango'
    password: 'testing123'
    connection_check_threshold: 10
    dbi_params:
    RaiseError: 1
    AutoCommit: 1
    log_queries: 1
